### ISSUE TITLE
对于移动端与PC 端事件处理感觉不太友好

### ISSUE THREAD

**Issue by Klaustype** [cocos/cocos-example-projects#243]
首先 用UA 来区分设备类型感觉不是很 靠谱 ，如果能开放用户配置设备类型选项更为友好
之前遇到的问题发现 mini盒子使用打包后web app 所有键盘鼠标事件不会执行导致 鼠标 无法操作 
查看源码发现导致问题的根本是
![image](https://user-images.githubusercontent.com/34526974/191449560-8fc125ef-707d-48c7-b279-dfcfe3c006b6.png)
是处理UA 进行了拦截  这导致用户必须修改源码才能进行使用 希望开放对应端口 这样就有用户主动选择更为友好
![image](https://user-images.githubusercontent.com/34526974/191449931-0852e223-1696-4105-8c0e-97e59f317d3b.png)

**Comment by PPpro** [comment]
3.x 应该没有这些逻辑了，请问你遇到问题是在哪个引擎版本呢

**Comment by Klaustype** [comment]
您好 我是在是用2.4.9 的时候发现的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 下午3:12
收件人: ***@***.***&gt;; 
抄送: "［ ·重-要-邮-件· ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cocos/cocos-example-projects] 对于移动端与PC 端事件处理感觉不太友好 (Issue #243)





 
3.x 应该没有这些逻辑了，请问你遇到问题是在哪个引擎版本呢

**Comment by PPpro** [comment]
嗯嗯。3.x 应该解决了的
2.x 建议可以通过定制引擎解决这个问题哈
